/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiSearchEntry { 'timestamp' : bigint, 'searchQuery' : string }
export type ExternalBlob = Uint8Array;
export interface Playlist {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'videoIds' : Array<bigint>,
}
export interface UserProfile { 'username' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoPost {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'videoBlob' : ExternalBlob,
  'thumbnailBlob' : ExternalBlob,
  'timestamp' : bigint,
  'uploader' : Principal,
}
export interface WatchHistoryEntry { 'watchedAt' : bigint, 'videoId' : bigint }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVideoToPlaylist' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAiSearchHistory' : ActorMethod<[], undefined>,
  'clearWatchHistory' : ActorMethod<[], undefined>,
  'createPlaylist' : ActorMethod<[string], bigint>,
  'createVideoPost' : ActorMethod<
    [string, string, ExternalBlob, ExternalBlob],
    bigint
  >,
  'deletePlaylist' : ActorMethod<[bigint], undefined>,
  'deleteVideoPost' : ActorMethod<[bigint], undefined>,
  'followCreator' : ActorMethod<[Principal], undefined>,
  'getAiSearchHistory' : ActorMethod<[], Array<AiSearchEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlaylist' : ActorMethod<[bigint], [] | [Playlist]>,
  'getSavedVideos' : ActorMethod<[], Array<bigint>>,
  'getSubscriptions' : ActorMethod<[], Array<Principal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsername' : ActorMethod<[], [] | [string]>,
  'getUsernameByPrincipal' : ActorMethod<[Principal], [] | [string]>,
  'getVideoPost' : ActorMethod<[bigint], [] | [VideoPost]>,
  'getWatchHistory' : ActorMethod<[], Array<WatchHistoryEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'isPremium' : ActorMethod<[], boolean>,
  'listMyPlaylists' : ActorMethod<[], Array<Playlist>>,
  'listVideoPosts' : ActorMethod<[], Array<VideoPost>>,
  'recordWatchHistory' : ActorMethod<[bigint], undefined>,
  'removeVideoFromPlaylist' : ActorMethod<[bigint, bigint], undefined>,
  'renamePlaylist' : ActorMethod<[bigint, string], undefined>,
  'saveAiSearchHistory' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveVideo' : ActorMethod<[bigint], undefined>,
  'setUsername' : ActorMethod<[string], undefined>,
  'unfollowCreator' : ActorMethod<[Principal], undefined>,
  'unsaveVideo' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];