/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AiSearchEntry = IDL.Record({
  'timestamp' : IDL.Int,
  'searchQuery' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'username' : IDL.Text });
export const ExtendedProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'expiryDate' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'cardholderName' : IDL.Opt(IDL.Text),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'maskedCardNumber' : IDL.Opt(IDL.Text),
});
export const Playlist = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'videoIds' : IDL.Vec(IDL.Nat),
});
export const VideoPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'videoBlob' : ExternalBlob,
  'thumbnailBlob' : ExternalBlob,
  'timestamp' : IDL.Int,
  'uploader' : IDL.Principal,
});
export const WatchHistoryEntry = IDL.Record({
  'watchedAt' : IDL.Int,
  'videoId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVideoToPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'clearAiSearchHistory' : IDL.Func([], [], []),
  'clearWatchHistory' : IDL.Func([], [], []),
  'createPlaylist' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createVideoPost' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'deletePlaylist' : IDL.Func([IDL.Nat], [], []),
  'deleteVideoPost' : IDL.Func([IDL.Nat], [], []),
  'followCreator' : IDL.Func([IDL.Principal], [], []),
  'getAiSearchHistory' : IDL.Func([], [IDL.Vec(AiSearchEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExtendedProfile' : IDL.Func([], [IDL.Opt(ExtendedProfile)], ['query']),
  'getPlaylist' : IDL.Func([IDL.Nat], [IDL.Opt(Playlist)], ['query']),
  'getSavedVideos' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getSubscriptions' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUsernameByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getVideoPost' : IDL.Func([IDL.Nat], [IDL.Opt(VideoPost)], ['query']),
  'getWatchHistory' : IDL.Func([], [IDL.Vec(WatchHistoryEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isPremium' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
  'listVideoPosts' : IDL.Func([], [IDL.Vec(VideoPost)], ['query']),
  'recordWatchHistory' : IDL.Func([IDL.Nat], [], []),
  'removeVideoFromPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'renamePlaylist' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveAiSearchHistory' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveExtendedProfile' : IDL.Func([ExtendedProfile], [], []),
  'saveVideo' : IDL.Func([IDL.Nat], [], []),
  'setUsername' : IDL.Func([IDL.Text], [], []),
  'unfollowCreator' : IDL.Func([IDL.Principal], [], []),
  'unsaveVideo' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AiSearchEntry = IDL.Record({
    'timestamp' : IDL.Int,
    'searchQuery' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text });
  const ExtendedProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'expiryDate' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'cardholderName' : IDL.Opt(IDL.Text),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'maskedCardNumber' : IDL.Opt(IDL.Text),
  });
  const Playlist = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'videoIds' : IDL.Vec(IDL.Nat),
  });
  const VideoPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'videoBlob' : ExternalBlob,
    'thumbnailBlob' : ExternalBlob,
    'timestamp' : IDL.Int,
    'uploader' : IDL.Principal,
  });
  const WatchHistoryEntry = IDL.Record({
    'watchedAt' : IDL.Int,
    'videoId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVideoToPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'clearAiSearchHistory' : IDL.Func([], [], []),
    'clearWatchHistory' : IDL.Func([], [], []),
    'createPlaylist' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createVideoPost' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'deletePlaylist' : IDL.Func([IDL.Nat], [], []),
    'deleteVideoPost' : IDL.Func([IDL.Nat], [], []),
    'followCreator' : IDL.Func([IDL.Principal], [], []),
    'getAiSearchHistory' : IDL.Func([], [IDL.Vec(AiSearchEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExtendedProfile' : IDL.Func([], [IDL.Opt(ExtendedProfile)], ['query']),
    'getPlaylist' : IDL.Func([IDL.Nat], [IDL.Opt(Playlist)], ['query']),
    'getSavedVideos' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getSubscriptions' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUsernameByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getVideoPost' : IDL.Func([IDL.Nat], [IDL.Opt(VideoPost)], ['query']),
    'getWatchHistory' : IDL.Func([], [IDL.Vec(WatchHistoryEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isPremium' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
    'listVideoPosts' : IDL.Func([], [IDL.Vec(VideoPost)], ['query']),
    'recordWatchHistory' : IDL.Func([IDL.Nat], [], []),
    'removeVideoFromPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'renamePlaylist' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveAiSearchHistory' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveExtendedProfile' : IDL.Func([ExtendedProfile], [], []),
    'saveVideo' : IDL.Func([IDL.Nat], [], []),
    'setUsername' : IDL.Func([IDL.Text], [], []),
    'unfollowCreator' : IDL.Func([IDL.Principal], [], []),
    'unsaveVideo' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };